# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='imgs.Image'),
            preserve_default=False,
        ),
    ]
