# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0003_auto_20170725_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
