# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0004_remove_comment_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='imgs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imgs.Image'),
        ),
    ]
