# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0005_comment_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='imgs',
        ),
    ]
